on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/setup-node@v1
        with:
          args: install
      - name: npm test
        uses: actions/setup-node@v1
        with:
          args: run test
      - name: npm lint
        uses: actions/setup-node@v1
        with:
          args: run lint
      - name: Publish to pkalkman/mve-workflowengine on Docker Hub 
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
            name: irt01/node-web-app
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            dockerfile: Dockerfile
            tags: 1
